#!/bin/bash
# Regenerate superdev/KB-STATUS.md — the agent-agnostic session briefing
# (Codex/OpenCode read this via AGENTS.md pointer; Claude also gets the live
# SessionStart injection). Called by the post-commit ship loop. Writes only
# when content actually changed, to avoid commit churn.
ROOT=$(git rev-parse --show-toplevel 2>/dev/null) || exit 0
KB=$ROOT/superdev
FORGE="${KBFORGE_HOME:-$HOME/superdev/kb-forge}"
[ -f "$KB/kb/derived/inventory.md" ] || exit 0

PIN=$(grep -m1 '^source_commit:' "$KB/kb/derived/inventory.md" | awk '{print $2}')
LAST=$(git -C "$ROOT" log -1 --format=%h -- . ':(exclude)superdev')
if [ "$PIN" = "$LAST" ]; then SYNC="in sync"; else
  SYNC="$(git -C "$ROOT" rev-list --count "$PIN..$LAST" -- . ':(exclude)superdev' 2>/dev/null || echo '?') code commit(s) behind"
fi
OPEN=$(grep -cE '^[0-9]+\.' "$KB/QUEUE.md" 2>/dev/null || echo '?')
LEDGER=$(ls "$KB/ledger" 2>/dev/null | grep -c . || echo 0)
. "$FORGE/session-kit/evals/telemetry-lib.sh" 2>/dev/null || kb_telemetry(){ :; }
kb_telemetry kb_status "queue=$OPEN ledger=$LEDGER"

TMP=$(mktemp)
{
  echo "<!-- auto-generated by the kb-forge ship loop — do not edit by hand -->"
  echo "# KB status"
  echo
  echo "- pin: \`$PIN\` | last code commit: \`$LAST\` ($SYNC)"
  echo "- open adjudication items: **$OPEN** (superdev/QUEUE.md)"
  echo "- ratified invariants:"
  grep -E '^#+ *INV-' "$KB/kb/normative/01-invariants.md" 2>/dev/null | sed 's/^#* */  - /'
  echo "- recall before building: \`python3 $FORGE/recall.py --config superdev/kbforge.yaml --files <repo-relative paths>\`"
  echo "- procedures: superdev-interview / superdev-recall / superdev-decide / superdev-diverge / superdev-ratify"
  echo "  (Claude: skills; Codex & OpenCode: /superdev-* commands)"
  [ -f "$KB/evals/health.md" ] && cat "$KB/evals/health.md"
} > "$TMP"
cmp -s "$TMP" "$KB/KB-STATUS.md" 2>/dev/null && { rm -f "$TMP"; exit 0; }
mv "$TMP" "$KB/KB-STATUS.md"
exit 0
